[package]
name = "tokio"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2024"

[dependencies]
ntex = { workspace = true, features = ["tokio"] }
ntex-files = { workspace = true }
ntex-session = { workspace = true }
ntex-rt = "3"
futures = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true, features = ["full"] }
