[package]
name = "awc_examples"
version = "5.0.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2024"

[dependencies]
ntex = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }
validator_derive = { workspace = true }
