[workspace]
resolver = "3"
members = [
   "async_db",
   "async_ex1",
   "async_ex2",
   "async_pg",
   "awc_https",
   "basics",
   "cookie-auth",
   "cookie-session",
#   "diesel",
   "docker_sample",
   "error_handling",
   "form",
   "graphql-demo",
   "hello-world",
   "http-proxy",
   "json",
   "json_error",
   "jsonrpc",
   "juniper",
   "middleware",
   "multipart",
   "openssl",
   "r2d2",
   "run-in-thread",
   "rustls",
   "server-sent-events",
   "shutdown-server",
#   "simple-auth-server",
   "state1",
   "state5",
   "static_index",
   "template_askama",
   "template_handlebars",
   "template_tera",
   "template_yarte",
   "todo",
   "tokio",
   "unix-socket",
   "websocket",
   "websocket-lowlevel",
   "websocket-chat",
   "websocket-tcp-chat",
]

[workspace.package]
edition = "2024"
rust-version = "1.95"

[workspace.dependencies]
ntex = "4.0.0-beta.14"
ntex-server = "4.1.0"
ntex-service = "5.0.0"
ntex-tls = "4.0.0"
ntex-util = "4.0.0"

ntex-cors = "4.0.0"
ntex-files = "4.0.0"
ntex-identity = "4.0.0"
ntex-session = "4.0.0"
ntex-multipart = "4.0.0"
ntex-multipart-derive = "4.0.0"

askama = "0.9"
bitflags = "2"
cookie = "0.18"
config = "0.10"
clap = "2.32"
deadpool-postgres = { version = "0.10", features = ["serde"] }
diesel = { version = "1.1", features = ["sqlite", "r2d2"] }
dotenv = "0.15"
derive_more = { version = "2.0.1", features = ["from", "display"] }
env_logger = "0.11"
futures = "0.3.34"
futures-test = "0.3.34"
handlebars = "3.0.0"
http = "1"
httpdate = "1.0"
httparse = "1.10"
json = "0.12"
juniper = "0.14"
language-tags = "0.3"
log = "0.4"
mime = "0.3"
mime_guess = "2.0"
num_cpus = "1.17"
openssl = "0.10"
percent-encoding = "2.1"
pin-project = "1.0"
regex = "1.12.3"
r2d2 = "0.8"
r2d2_sqlite = "0.14"
r2d2_mysql = "17.0"
rand = "0.8"
rusqlite = "0.21"
serde = "1"
serde_json = "1"
serde_derive = "1"
serde_plain = "1"
tokio-pg-mapper = "0.2"
tokio-pg-mapper-derive = "0.2"
tokio-postgres = "0.7"
twoway = "0.2"
tempfile = "3.4"
tera = "1.0"
thiserror = "2"
time = { version = "0.3.54", default-features = false, features = ["std"] }
tokio = "1"
validator = "0.10"
validator_derive = "0.10"
v_htmlescape = "0.15"
yarte = { version = "0.15", features = ["html-min"]  }
url = "2.1"
unicase = "2.6"
uuid = { version = "1", features = ["serde", "v4"] }

[profile.release]
panic = 'abort'
