[package]
name = "multipart-example"
version = "4.0.0"
authors = ["Bevan Hunt <bevan@bevanhunt.com>"]
edition = "2024"
license = "MIT"
description = "Simple file uploader in Ntex with Async/Await"
keywords = ["ntex", "multipart"]
repository = "https://github.com/ntex/examples"
readme = "README.md"

[dependencies]
ntex = { workspace = true }
ntex-multipart = { workspace = true }
futures = { workspace = true }
