[package]
name = "r2d2-example"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2024"

[dependencies]
ntex = { workspace = true, features = ["tokio"] }

futures = { workspace = true }
env_logger = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

r2d2 = { workspace = true }
r2d2_sqlite = { workspace = true }
rusqlite = { workspace = true }
