[package]
name = "error_handling"
version = "4.0.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2024"

[dependencies]
ntex = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
env_logger = { workspace = true }
