[package]
name = "rustls-example"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2024"

[[bin]]
name = "rustls-server"
path = "src/main.rs"

[dependencies]
env_logger = { workspace = true }
rustls = "0.23"
rustls-pemfile = "2"
ntex = { workspace = true, features = ["rustls", "tokio"] }
ntex-files = { workspace = true }
