[package]
name = "shutdown-server"
version = "4.0.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2024"
description = "Send a request to the server to shut it down"

[dependencies]
ntex = { workspace = true, features = ["tokio"] }
env_logger = { workspace = true }
futures = { workspace = true }
