[package]
name = "websocket-chat"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2024"

[[bin]]
name = "websocket-chat-server"
path = "src/main.rs"

[dependencies]
ntex = { workspace = true }
ntex-files = { workspace = true }

rand = { workspace = true }
futures = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
