[package]
name = "chat-example"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2024"

[[bin]]
name = "websocket-tcp-chat-server"
path = "src/main.rs"

[[bin]]
name = "websocket-tcp-chat-client"
path = "src/client-ws.rs"

[[bin]]
name = "websocket-tcp-chat-tcp-client"
path = "src/client-tcp.rs"

[dependencies]
ntex = { workspace = true, features = ["tokio"] }
ntex-mqtt = "9.0"
ntex-amqp = "6.0"
ntex-files = { workspace = true }

rand = { workspace = true }
byteorder = "1.4"
futures = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
