[package]
name = "websocket"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2024"

[[bin]]
name = "websocket-server"
path = "src/main.rs"

[[bin]]
name = "websocket-client"
path = "src/client.rs"

[dependencies]
ntex = { workspace = true }
ntex-files = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
